export const SERVICE_PRICES = {
  EXPRESS: 35000,
  BASIC: 45000,
  FULL: 75000,
  PREMIUM: 120000,
};

export const VALID_TRANSITIONS = {
  PENDING: ['IN_PROGRESS', 'CANCELLED'],
  IN_PROGRESS: ['COMPLETED', 'CANCELLED'],
};

export const CUSTOMER_TYPES = ['FREQUENT', 'CORPORATE', 'OCCASIONAL'];

export const PAYMENT_METHODS = ['CASH', 'NEQUI', 'DAVIPLATA', 'DEBIT', 'CREDIT'];

export const SERVICE_TYPES = Object.keys(SERVICE_PRICES);
