export const SERVICE_PRICES = {
  EXPRESS: 35000,
  BASIC:   45000,
  FULL:    75000,
  PREMIUM: 120000,
};

export const VALID_TRANSITIONS = {
  PENDING:     ['IN_PROGRESS', 'CANCELLED'],
  IN_PROGRESS: ['COMPLETED', 'CANCELLED'],
};
